# Generated by Django 5.1.5 on 2025-01-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agno', models.CharField(max_length=6)),
                ('home', models.CharField(max_length=50)),
                ('away', models.CharField(max_length=50)),
                ('score_0', models.CharField(max_length=10)),
                ('score_1', models.CharField(max_length=10)),
                ('tournament', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=10)),
                ('away', models.CharField(max_length=50)),
                ('agno', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('Pts', models.CharField(max_length=6)),
                ('PJ', models.CharField(max_length=6)),
                ('PG', models.CharField(max_length=6)),
                ('PE', models.CharField(max_length=6)),
                ('PP', models.CharField(max_length=6)),
                ('GF', models.CharField(max_length=6)),
                ('GC', models.CharField(max_length=6)),
                ('Dif', models.CharField(max_length=6)),
                ('Grupo', models.CharField(max_length=50)),
                ('agno', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=6)),
                ('away', models.CharField(max_length=50)),
                ('agno', models.CharField(max_length=4)),
            ],
        ),
    ]
